### ISSUE TITLE
Reduce crate dependencies

### ISSUE THREAD

**Issue by connor4312** [segevfiner/keepawake-rs#3]
This repo has both a binary as well as a cargo crate. Right now, the [crate](https://docs.rs/crate/keepawake/0.1.3) has dependencies on clap and other packages that are only used by the CLI. It would be nice if the crate and CLI could be broken into separate packages to reduce these 🙂

**Comment by segevfiner** [comment]
Yay for the lack of https://github.com/rust-lang/cargo/issues/1982 defeating the purpose of having both a binary and library in the same package... I assume this requires a cargo workspace with two separate crates, just need to come up with proper names for them, any convention for this?

**Comment by connor4312** [comment]
Probably. https://github.com/warp-tech/russh is a project I've worked in that has multiple crates (though no CLI). https://github.com/BurntSushi/ripgrep is a less trivial example.

**Comment by segevfiner** [comment]
Primarily the issue is that I wanted users to be able to `cargo install keepawake` to get the CLI, and also possibly use the library crate via `keepawake`, that is, the same name, rather than having to go with an artificial `keepawake-cli` crate. Granted, the library part was written to serve the CLI and probably isn't a perfect API for consumers yet.

**Comment by connor4312** [comment]
Naming is hard. Maybe the crate could just something like `keepawake-util`? At least there's some prior art with things like tokio-util and crossbeam-utils.

**Comment by segevfiner** [comment]
Posted in https://users.rust-lang.org/t/whats-the-convention-for-handling-a-hybrid-library-and-binary-crates-dependencies/84174
